import { addIcons } from 'ionicons';
import {
  addOutline,
  analyticsOutline,
  appsOutline,
  businessOutline,
  calendarOutline,
  cartOutline,
  cashOutline,
  checkmarkDoneOutline,
  checkmarkOutline,
  chevronBackOutline,
  chevronDownOutline,
  chevronForwardOutline,
  clipboardOutline,
  constructOutline,
  createOutline,
  cubeOutline,
  documentTextOutline,
  downloadOutline,
  ellipsisHorizontal,
  eyeOutline,
  fishOutline,
  giftOutline,
  gridOutline,
  idCardOutline,
  informationCircleOutline,
  keyOutline,
  layersOutline,
  leafOutline,
  mapOutline,
  medicalOutline,
  medkitOutline,
  menuOutline,
  navigateOutline,
  notificationsOutline,
  nutritionOutline,
  optionsOutline,
  pawOutline,
  peopleOutline,
  pricetagsOutline,
  qrCodeOutline,
  searchOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  swapVerticalOutline,
  walletOutline,
  warningOutline,
  waterOutline
} from 'ionicons/icons';

/** Register every Ionicon referenced by the Web application. */
export function registerIonicons(): void {
  addIcons({
    'add-outline': addOutline,
    'analytics-outline': analyticsOutline,
    'apps-outline': appsOutline,
    'business-outline': businessOutline,
    'calendar-outline': calendarOutline,
    'cart-outline': cartOutline,
    'cash-outline': cashOutline,
    'checkmark-done-outline': checkmarkDoneOutline,
    'checkmark-outline': checkmarkOutline,
    'chevron-back-outline': chevronBackOutline,
    'chevron-down-outline': chevronDownOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'clipboard-outline': clipboardOutline,
    'construct-outline': constructOutline,
    'create-outline': createOutline,
    'cube-outline': cubeOutline,
    'document-text-outline': documentTextOutline,
    'download-outline': downloadOutline,
    'ellipsis-horizontal': ellipsisHorizontal,
    'eye-outline': eyeOutline,
    'fish-outline': fishOutline,
    'gift-outline': giftOutline,
    'grid-outline': gridOutline,
    'id-card-outline': idCardOutline,
    'information-circle-outline': informationCircleOutline,
    'key-outline': keyOutline,
    'layers-outline': layersOutline,
    'leaf-outline': leafOutline,
    'map-outline': mapOutline,
    'medical-outline': medicalOutline,
    'medkit-outline': medkitOutline,
    'menu-outline': menuOutline,
    'navigate-outline': navigateOutline,
    'notifications-outline': notificationsOutline,
    'nutrition-outline': nutritionOutline,
    'options-outline': optionsOutline,
    'paw-outline': pawOutline,
    'people-outline': peopleOutline,
    'pricetags-outline': pricetagsOutline,
    'qr-code-outline': qrCodeOutline,
    'search-outline': searchOutline,
    'settings-outline': settingsOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'swap-vertical-outline': swapVerticalOutline,
    'wallet-outline': walletOutline,
    'warning-outline': warningOutline,
    'water-outline': waterOutline
  });
}
